COMMON_FLAGS="-march=znver4 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=znver4"

# NOTE: This stage was built with the bindist USE flag enabled

MAKEOPTS="-j24 -l20"
EMERGE_DEFAULT_OPTS="--jobs=6 --load-average=20"

USE="wayland X elogind opengl dbus vulkan"

ACCEPT_LICENSE="*"
FEATURES="${FEATURES} buildpkg parallel-install"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
