# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist USE flag enabled

MAKEOPTS="-j28 -l26"
EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=26"

USE="wayland X pipewire alsa elogind opengl dbus ffmpeg gstreamer vulkan vaapi gles gtk"

ACCEPT_LICENSE="*"
FEATURES="${FEATURES} binpkg-request-signature getbinpkg ebuild-locks parallel-install"
# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
